UPDATE public.profiles SET full_name='Green Earth Foundation' WHERE id='d89ec023-8f4e-40f2-94f3-0a98a95b2f7e';
UPDATE public.ngos SET organization_name='Green Earth Foundation', focus_area='Environment', mission=$$Protecting biodiversity and reforesting degraded land.$$, address='Bengaluru, India', contact_email='hello@greenearthfoundation.org', website='https://greenearthfoundation.org' WHERE profile_id='d89ec023-8f4e-40f2-94f3-0a98a95b2f7e';
UPDATE public.profiles SET full_name='Bright Futures Trust' WHERE id='2bf7af34-b941-4f04-a520-1cfcafd987a4';
UPDATE public.ngos SET organization_name='Bright Futures Trust', focus_area='Education', mission=$$Free after-school programs for underserved children.$$, address='Mumbai, India', contact_email='hello@brightfuturestrust.org', website='https://brightfuturestrust.org' WHERE profile_id='2bf7af34-b941-4f04-a520-1cfcafd987a4';
UPDATE public.profiles SET full_name='HealthBridge Initiative' WHERE id='2bea549e-8fa4-46b0-8853-dca2ae5e8495';
UPDATE public.ngos SET organization_name='HealthBridge Initiative', focus_area='Healthcare', mission=$$Mobile clinics for rural and semi-urban communities.$$, address='Chennai, India', contact_email='hello@healthbridgeinitiative.org', website='https://healthbridgeinitiative.org' WHERE profile_id='2bea549e-8fa4-46b0-8853-dca2ae5e8495';
UPDATE public.profiles SET full_name='Ocean Guardians' WHERE id='9166ee28-77c0-41d2-b5ee-a76d8ab81a23';
UPDATE public.ngos SET organization_name='Ocean Guardians', focus_area='Environment', mission=$$Coastal cleanups and marine plastic recovery.$$, address='Kochi, India', contact_email='hello@oceanguardians.org', website='https://oceanguardians.org' WHERE profile_id='9166ee28-77c0-41d2-b5ee-a76d8ab81a23';
UPDATE public.profiles SET full_name='Skill Rise Collective' WHERE id='24ed4bd9-eb19-473e-96e7-54f07d505821';
UPDATE public.ngos SET organization_name='Skill Rise Collective', focus_area='Livelihoods', mission=$$Vocational training for women and youth.$$, address='Pune, India', contact_email='hello@skillrisecollective.org', website='https://skillrisecollective.org' WHERE profile_id='24ed4bd9-eb19-473e-96e7-54f07d505821';
UPDATE public.profiles SET full_name='Nourish Now' WHERE id='1391a183-2605-49cd-b2cc-b86bcf9bb130';
UPDATE public.ngos SET organization_name='Nourish Now', focus_area='Hunger Relief', mission=$$Community kitchens and meal-distribution networks.$$, address='Delhi, India', contact_email='hello@nourishnow.org', website='https://nourishnow.org' WHERE profile_id='1391a183-2605-49cd-b2cc-b86bcf9bb130';
UPDATE public.profiles SET full_name='Code for Good' WHERE id='431f1972-0765-4d5d-8d08-da11e989860a';
UPDATE public.ngos SET organization_name='Code for Good', focus_area='Technology', mission=$$Digital literacy and coding bootcamps in low-income schools.$$, address='Hyderabad, India', contact_email='hello@codeforgood.org', website='https://codeforgood.org' WHERE profile_id='431f1972-0765-4d5d-8d08-da11e989860a';
UPDATE public.profiles SET full_name='Elder Care Circle' WHERE id='9050fd52-a11c-4087-a50e-50b766a5f8ef';
UPDATE public.ngos SET organization_name='Elder Care Circle', focus_area='Elderly Support', mission=$$Companionship and welfare for senior citizens.$$, address='Kolkata, India', contact_email='hello@eldercarecircle.org', website='https://eldercarecircle.org' WHERE profile_id='9050fd52-a11c-4087-a50e-50b766a5f8ef';
UPDATE public.profiles SET full_name='Wings for Girls' WHERE id='0317c5f2-846d-46ef-ad4b-6b6583f83a8b';
UPDATE public.ngos SET organization_name='Wings for Girls', focus_area='Women Empowerment', mission=$$Mentorship, safety training, and STEM outreach.$$, address='Jaipur, India', contact_email='hello@wingsforgirls.org', website='https://wingsforgirls.org' WHERE profile_id='0317c5f2-846d-46ef-ad4b-6b6583f83a8b';
UPDATE public.profiles SET full_name='Paws & Refuge' WHERE id='81d6edbc-ffee-4c8c-bf45-2c3432d51b1b';
UPDATE public.ngos SET organization_name='Paws & Refuge', focus_area='Animal Welfare', mission=$$Street-animal rescue, sterilization, and adoption.$$, address='Ahmedabad, India', contact_email='hello@pawsrefuge.org', website='https://pawsrefuge.org' WHERE profile_id='81d6edbc-ffee-4c8c-bf45-2c3432d51b1b';

UPDATE public.profiles SET full_name='Aarav Sharma', location='Bengaluru, India' WHERE id='0563d8ee-8b2c-4759-9cba-5ca37fac8325';
UPDATE public.volunteers SET skills=ARRAY['Teaching','Carpentry','Data Analysis']::text[], interests=ARRAY['Women Empowerment','Healthcare']::text[], availability='Fully flexible, 10+ hours', experience=$$Organized 6 beach cleanups and led a college eco-club for 3 semesters.$$, preferred_location='Bengaluru, India' WHERE profile_id='0563d8ee-8b2c-4759-9cba-5ca37fac8325';
UPDATE public.profiles SET full_name='Isha Menon', location='Mumbai, India' WHERE id='11375c65-59c0-4a04-849d-fed046e0d6ff';
UPDATE public.volunteers SET skills=ARRAY['Counseling','Fundraising','Curriculum Development']::text[], interests=ARRAY['Education','Women Empowerment']::text[], availability='Weekday evenings, 2 hours', experience=$$New volunteer — eager, dependable, and ready to contribute.$$, preferred_location='Mumbai, India' WHERE profile_id='11375c65-59c0-4a04-849d-fed046e0d6ff';
UPDATE public.profiles SET full_name='Rohan Kapoor', location='Chennai, India' WHERE id='16f218d7-f6eb-4fbf-9e98-244cc034364c';
UPDATE public.volunteers SET skills=ARRAY['Marketing','Content Writing','Gardening']::text[], interests=ARRAY['Mental Health','Technology','Elderly Support','Women Empowerment']::text[], availability='Saturdays only, full-day', experience=$$Trained as a first responder; supported 3 mobile health camps.$$, preferred_location='Chennai, India' WHERE profile_id='16f218d7-f6eb-4fbf-9e98-244cc034364c';
UPDATE public.profiles SET full_name='Priya Das', location='Delhi, India' WHERE id='404d9b38-1da9-48cb-9eb9-14ade68b5164';
UPDATE public.volunteers SET skills=ARRAY['Music','Yoga Instruction','Photography']::text[], interests=ARRAY['Elderly Support','Hunger Relief','Animal Welfare','Healthcare']::text[], availability='Weekday evenings, 2 hours', experience=$$Designed brand assets and social content for two nonprofits.$$, preferred_location='Delhi, India' WHERE profile_id='404d9b38-1da9-48cb-9eb9-14ade68b5164';
UPDATE public.profiles SET full_name='Vikram Rao', location='Pune, India' WHERE id='4b66ffe3-cbdb-4a9d-9e7b-f59839348e77';
UPDATE public.volunteers SET skills=ARRAY['Mentoring','Translation','Web Development']::text[], interests=ARRAY['Disability Rights','Hunger Relief','Sports']::text[], availability='Flexible, 8 hours/week', experience=$$Volunteered for 2 years with local reading programs, mentored 15+ students.$$, preferred_location='Pune, India' WHERE profile_id='4b66ffe3-cbdb-4a9d-9e7b-f59839348e77';
UPDATE public.profiles SET full_name='Ananya Chopra', location='Hyderabad, India' WHERE id='5770ab7f-bfc9-486b-b683-d214460a54cf';
UPDATE public.volunteers SET skills=ARRAY['Marketing','Web Development','Translation','Mentoring','Yoga Instruction','Public Speaking']::text[], interests=ARRAY['Sports','Disability Rights','Hunger Relief','Climate Action']::text[], availability='Weekday evenings, 2 hours', experience=$$Organized 6 beach cleanups and led a college eco-club for 3 semesters.$$, preferred_location='Hyderabad, India' WHERE profile_id='5770ab7f-bfc9-486b-b683-d214460a54cf';
UPDATE public.profiles SET full_name='Kabir Bhat', location='Kolkata, India' WHERE id='6688a787-ee05-4a91-b171-b32c06c5dc0c';
UPDATE public.volunteers SET skills=ARRAY['Driving','Social Media','Music']::text[], interests=ARRAY['Education','Disability Rights','Women Empowerment']::text[], availability='Weekends, 4-6 hours', experience=$$Led fundraising drives that raised INR 4L for animal shelters.$$, preferred_location='Kolkata, India' WHERE profile_id='6688a787-ee05-4a91-b171-b32c06c5dc0c';
UPDATE public.profiles SET full_name='Meera Ghosh', location='Jaipur, India' WHERE id='81b5d4fa-2098-4f55-8b1a-1256579107c9';
UPDATE public.volunteers SET skills=ARRAY['Community Outreach','Cooking','First Aid','Photography','Content Writing']::text[], interests=ARRAY['Animal Welfare','Mental Health','Arts','Rural Development']::text[], availability='Weekends, 4-6 hours', experience=$$Delivered coding workshops to over 200 students across 4 schools.$$, preferred_location='Jaipur, India' WHERE profile_id='81b5d4fa-2098-4f55-8b1a-1256579107c9';
UPDATE public.profiles SET full_name='Aditya Dutta', location='Ahmedabad, India' WHERE id='99b27090-a391-4a57-9739-73653445ed79';
UPDATE public.volunteers SET skills=ARRAY['Photography','Community Outreach','Translation','Data Analysis']::text[], interests=ARRAY['Mental Health','Technology','Women Empowerment','Arts']::text[], availability='Flexible, 8 hours/week', experience=$$Volunteered for 2 years with local reading programs, mentored 15+ students.$$, preferred_location='Ahmedabad, India' WHERE profile_id='99b27090-a391-4a57-9739-73653445ed79';
UPDATE public.profiles SET full_name='Sara Shah', location='Kochi, India' WHERE id='ac7a785f-7246-4ebd-a27a-375b31fa7bdb';
UPDATE public.volunteers SET skills=ARRAY['Curriculum Development','Yoga Instruction','Event Planning','Translation']::text[], interests=ARRAY['Education','Women Empowerment','Sports']::text[], availability='Fully flexible, 10+ hours', experience=$$Designed brand assets and social content for two nonprofits.$$, preferred_location='Kochi, India' WHERE profile_id='ac7a785f-7246-4ebd-a27a-375b31fa7bdb';
UPDATE public.profiles SET full_name='Dev Saxena', location='Bengaluru, India' WHERE id='bc10a404-6064-4b93-9279-8bb30ccf646e';
UPDATE public.volunteers SET skills=ARRAY['Cooking','Video Editing','Translation','Community Outreach']::text[], interests=ARRAY['Animal Welfare','Healthcare']::text[], availability='Weekday evenings, 2 hours', experience=$$New volunteer — eager, dependable, and ready to contribute.$$, preferred_location='Bengaluru, India' WHERE profile_id='bc10a404-6064-4b93-9279-8bb30ccf646e';
UPDATE public.profiles SET full_name='Nisha Patel', location='Mumbai, India' WHERE id='bdaa7484-d771-4925-81d6-4633d869fa66';
UPDATE public.volunteers SET skills=ARRAY['Carpentry','Counseling','Fundraising','Translation','First Aid']::text[], interests=ARRAY['Healthcare','Technology']::text[], availability='Saturdays only, full-day', experience=$$Organized 6 beach cleanups and led a college eco-club for 3 semesters.$$, preferred_location='Mumbai, India' WHERE profile_id='bdaa7484-d771-4925-81d6-4633d869fa66';
UPDATE public.profiles SET full_name='Arjun Reddy', location='Chennai, India' WHERE id='c6c4b749-c926-4f9d-a21d-afb2bf164896';
UPDATE public.volunteers SET skills=ARRAY['Web Development','Graphic Design','Cooking']::text[], interests=ARRAY['Rural Development','Arts']::text[], availability='Saturdays only, full-day', experience=$$Organized 6 beach cleanups and led a college eco-club for 3 semesters.$$, preferred_location='Chennai, India' WHERE profile_id='c6c4b749-c926-4f9d-a21d-afb2bf164896';
UPDATE public.profiles SET full_name='Riya Verma', location='Delhi, India' WHERE id='caa327f5-0844-4c48-b431-f611f02671ee';
UPDATE public.volunteers SET skills=ARRAY['Translation','Project Management','Community Outreach','Illustration','Data Analysis','Marketing']::text[], interests=ARRAY['Arts','Mental Health']::text[], availability='Weekends, 4-6 hours', experience=$$New volunteer — eager, dependable, and ready to contribute.$$, preferred_location='Delhi, India' WHERE profile_id='caa327f5-0844-4c48-b431-f611f02671ee';
UPDATE public.profiles SET full_name='Karan Bose', location='Pune, India' WHERE id='d1c60597-221f-40a0-9d39-ff572ba65021';
UPDATE public.volunteers SET skills=ARRAY['Music','Cooking','Event Planning','Web Development','Public Speaking']::text[], interests=ARRAY['Healthcare','Livelihoods','Environment']::text[], availability='Fully flexible, 10+ hours', experience=$$Trained as a first responder; supported 3 mobile health camps.$$, preferred_location='Pune, India' WHERE profile_id='d1c60597-221f-40a0-9d39-ff572ba65021';
UPDATE public.profiles SET full_name='Diya Mehta', location='Hyderabad, India' WHERE id='d4d4db6a-0334-4140-8c90-cfa6b4f63fdc';
UPDATE public.volunteers SET skills=ARRAY['Illustration','Web Development','Cooking','Public Speaking']::text[], interests=ARRAY['Technology','Sports','Women Empowerment','Healthcare']::text[], availability='Flexible, 8 hours/week', experience=$$Delivered coding workshops to over 200 students across 4 schools.$$, preferred_location='Hyderabad, India' WHERE profile_id='d4d4db6a-0334-4140-8c90-cfa6b4f63fdc';
UPDATE public.profiles SET full_name='Yash Gupta', location='Kolkata, India' WHERE id='d9474b81-6721-40fe-bd9e-151f99be3483';
UPDATE public.volunteers SET skills=ARRAY['Project Management','Event Planning','Video Editing']::text[], interests=ARRAY['Education','Hunger Relief']::text[], availability='Flexible, 8 hours/week', experience=$$Ran weekly community-kitchen shifts serving 300+ meals.$$, preferred_location='Kolkata, India' WHERE profile_id='d9474b81-6721-40fe-bd9e-151f99be3483';
UPDATE public.profiles SET full_name='Tara Sen', location='Jaipur, India' WHERE id='ee306deb-8894-4a4a-b654-0656e4d98a22';
UPDATE public.volunteers SET skills=ARRAY['Social Media','Counseling','Mentoring']::text[], interests=ARRAY['Mental Health','Livelihoods']::text[], availability='Weekends, 4-6 hours', experience=$$New volunteer — eager, dependable, and ready to contribute.$$, preferred_location='Jaipur, India' WHERE profile_id='ee306deb-8894-4a4a-b654-0656e4d98a22';

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','a8e56e0c-20de-435d-a031-d750c40db9b4','authenticated','authenticated','demo.vol01@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Ananya Patel"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('a8e56e0c-20de-435d-a031-d750c40db9b4','volunteer','Ananya Patel','Delhi, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('a8e56e0c-20de-435d-a031-d750c40db9b4',ARRAY['Marketing','Photography','Data Analysis','Illustration','Project Management','Fundraising']::text[],ARRAY['Climate Action','Technology']::text[],'Fully flexible, 10+ hours',$$Ran weekly community-kitchen shifts serving 300+ meals.$$,'Delhi, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','fec21bbe-6624-4bfa-8fcc-a39ab683d2e6','authenticated','authenticated','demo.vol02@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Kabir Singh"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('fec21bbe-6624-4bfa-8fcc-a39ab683d2e6','volunteer','Kabir Singh','Pune, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('fec21bbe-6624-4bfa-8fcc-a39ab683d2e6',ARRAY['Community Outreach','Illustration','Web Development','Social Media','Mentoring']::text[],ARRAY['Environment','Sports','Technology']::text[],'Weekday evenings, 2 hours',$$Ran weekly community-kitchen shifts serving 300+ meals.$$,'Pune, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','a18ff6b6-b535-406e-922c-9a5601d74256','authenticated','authenticated','demo.vol03@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Meera Chopra"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('a18ff6b6-b535-406e-922c-9a5601d74256','volunteer','Meera Chopra','Hyderabad, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('a18ff6b6-b535-406e-922c-9a5601d74256',ARRAY['Social Media','Mentoring','Curriculum Development']::text[],ARRAY['Education','Technology','Women Empowerment']::text[],'Flexible, 8 hours/week',$$Facilitated STEM workshops for girls in grades 6-10.$$,'Hyderabad, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','b92da22b-21df-406f-8a0b-3c3336d8393a','authenticated','authenticated','demo.vol04@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Aditya Kaur"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('b92da22b-21df-406f-8a0b-3c3336d8393a','volunteer','Aditya Kaur','Kolkata, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('b92da22b-21df-406f-8a0b-3c3336d8393a',ARRAY['Counseling','Video Editing','Social Media','Music','Fundraising','Content Writing','Web Development']::text[],ARRAY['Arts','Elderly Support']::text[],'Flexible, 8 hours/week',$$Led fundraising drives that raised INR 4L for animal shelters.$$,'Kolkata, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','baa4b71a-dd24-47ac-b78e-edb3693dffbc','authenticated','authenticated','demo.vol05@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Sara Banerjee"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('baa4b71a-dd24-47ac-b78e-edb3693dffbc','volunteer','Sara Banerjee','Jaipur, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('baa4b71a-dd24-47ac-b78e-edb3693dffbc',ARRAY['Driving','Cooking','Web Development']::text[],ARRAY['Elderly Support','Mental Health']::text[],'Flexible, 8 hours/week',$$Organized 6 beach cleanups and led a college eco-club for 3 semesters.$$,'Jaipur, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','894a05e4-30b1-47ef-b10c-0c003fa7f104','authenticated','authenticated','demo.vol06@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Dev Reddy"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('894a05e4-30b1-47ef-b10c-0c003fa7f104','volunteer','Dev Reddy','Ahmedabad, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('894a05e4-30b1-47ef-b10c-0c003fa7f104',ARRAY['Graphic Design','Fundraising','Photography','Data Analysis','Community Outreach','Social Media']::text[],ARRAY['Livelihoods','Rural Development']::text[],'Weekday mornings, 3 hours',$$Organized 6 beach cleanups and led a college eco-club for 3 semesters.$$,'Ahmedabad, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','8a63f881-ffd0-49d5-a6f2-f7b80cf35b58','authenticated','authenticated','demo.vol07@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Nisha Nair"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('8a63f881-ffd0-49d5-a6f2-f7b80cf35b58','volunteer','Nisha Nair','Kochi, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('8a63f881-ffd0-49d5-a6f2-f7b80cf35b58',ARRAY['Mentoring','Music','Social Media']::text[],ARRAY['Elderly Support','Livelihoods']::text[],'Saturdays only, full-day',$$Ran weekly community-kitchen shifts serving 300+ meals.$$,'Kochi, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','0f02bad0-e706-4ef4-a6aa-9385dd59ba71','authenticated','authenticated','demo.vol08@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Arjun Bhat"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('0f02bad0-e706-4ef4-a6aa-9385dd59ba71','volunteer','Arjun Bhat','Bengaluru, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('0f02bad0-e706-4ef4-a6aa-9385dd59ba71',ARRAY['Translation','Teaching','Data Analysis','Yoga Instruction']::text[],ARRAY['Animal Welfare','Elderly Support','Mental Health']::text[],'Fully flexible, 10+ hours',$$New volunteer — eager, dependable, and ready to contribute.$$,'Bengaluru, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','27a0c3d7-7c96-4f79-b7e9-9acaa97065e1','authenticated','authenticated','demo.vol09@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Riya Naidu"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('27a0c3d7-7c96-4f79-b7e9-9acaa97065e1','volunteer','Riya Naidu','Mumbai, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('27a0c3d7-7c96-4f79-b7e9-9acaa97065e1',ARRAY['Public Speaking','Content Writing','Curriculum Development','Counseling']::text[],ARRAY['Technology','Environment','Mental Health','Hunger Relief']::text[],'Weekends, 4-6 hours',$$Volunteered for 2 years with local reading programs, mentored 15+ students.$$,'Mumbai, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','eb5cf467-80ba-4d64-ba0e-cfea958ca9ba','authenticated','authenticated','demo.vol10@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Karan Sharma"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('eb5cf467-80ba-4d64-ba0e-cfea958ca9ba','volunteer','Karan Sharma','Chennai, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('eb5cf467-80ba-4d64-ba0e-cfea958ca9ba',ARRAY['Photography','Curriculum Development','Illustration','Mentoring','Yoga Instruction','Gardening','Project Management']::text[],ARRAY['Arts','Disability Rights']::text[],'Weekday evenings, 2 hours',$$Led fundraising drives that raised INR 4L for animal shelters.$$,'Chennai, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','91d63f78-e3e9-4e99-b10c-718b1eb0e38a','authenticated','authenticated','demo.vol11@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Diya Verma"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('91d63f78-e3e9-4e99-b10c-718b1eb0e38a','volunteer','Diya Verma','Delhi, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('91d63f78-e3e9-4e99-b10c-718b1eb0e38a',ARRAY['Counseling','Project Management','Curriculum Development','Mentoring']::text[],ARRAY['Arts','Sports','Disability Rights']::text[],'Weekday mornings, 3 hours',$$Designed brand assets and social content for two nonprofits.$$,'Delhi, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','ab73295b-344a-44b8-82c1-8a62ef48e8d5','authenticated','authenticated','demo.vol12@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Yash Joshi"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('ab73295b-344a-44b8-82c1-8a62ef48e8d5','volunteer','Yash Joshi','Pune, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('ab73295b-344a-44b8-82c1-8a62ef48e8d5',ARRAY['Social Media','Data Analysis','Translation','Graphic Design','Driving']::text[],ARRAY['Animal Welfare','Livelihoods','Hunger Relief','Education']::text[],'Weekends, 4-6 hours',$$Facilitated STEM workshops for girls in grades 6-10.$$,'Pune, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','ff002d4d-9020-49e4-bf9a-b5c29f044aed','authenticated','authenticated','demo.vol13@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Tara Ghosh"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('ff002d4d-9020-49e4-bf9a-b5c29f044aed','volunteer','Tara Ghosh','Hyderabad, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('ff002d4d-9020-49e4-bf9a-b5c29f044aed',ARRAY['Mentoring','Marketing','Content Writing']::text[],ARRAY['Animal Welfare','Healthcare','Hunger Relief','Education']::text[],'Weekday evenings, 2 hours',$$Designed brand assets and social content for two nonprofits.$$,'Hyderabad, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','d5704f32-702c-4d20-a862-18b848f4ef12','authenticated','authenticated','demo.vol14@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Nikhil Trivedi"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('d5704f32-702c-4d20-a862-18b848f4ef12','volunteer','Nikhil Trivedi','Kolkata, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('d5704f32-702c-4d20-a862-18b848f4ef12',ARRAY['Gardening','Public Speaking','Project Management','Cooking','Illustration','Teaching','Marketing']::text[],ARRAY['Climate Action','Arts','Education']::text[],'Weekday evenings, 2 hours',$$Trained as a first responder; supported 3 mobile health camps.$$,'Kolkata, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','be0f051b-1b66-45a9-a3c4-36571d8cbbac','authenticated','authenticated','demo.vol15@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Aisha Menon"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('be0f051b-1b66-45a9-a3c4-36571d8cbbac','volunteer','Aisha Menon','Jaipur, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('be0f051b-1b66-45a9-a3c4-36571d8cbbac',ARRAY['Graphic Design','Data Analysis','Public Speaking','Project Management','Content Writing','Event Planning','Driving']::text[],ARRAY['Arts','Disability Rights','Animal Welfare','Technology']::text[],'Saturdays only, full-day',$$Trained as a first responder; supported 3 mobile health camps.$$,'Jaipur, India') ON CONFLICT (profile_id) DO NOTHING;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000','0d01280f-d89a-40c0-a87d-1c78e7c421c7','authenticated','authenticated','demo.vol16@impactlink.demo',crypt('DemoPass!123', gen_salt('bf')),now(),now(),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Rahul Bose"}',false,'','','','')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.profiles (id, role, full_name, location) VALUES ('0d01280f-d89a-40c0-a87d-1c78e7c421c7','volunteer','Rahul Bose','Ahmedabad, India') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.volunteers (profile_id, skills, interests, availability, experience, preferred_location) VALUES ('0d01280f-d89a-40c0-a87d-1c78e7c421c7',ARRAY['Cooking','Fundraising','Data Analysis']::text[],ARRAY['Environment','Hunger Relief']::text[],'Weekday evenings, 2 hours',$$Trained as a first responder; supported 3 mobile health camps.$$,'Ahmedabad, India') ON CONFLICT (profile_id) DO NOTHING;